image: Visual Studio 2017
environment:
 nodejs_version: "9"
platform: x64
configuration: Release
install:
 - ps: Install-Product node $env:nodejs_version $env:platform
build_script:
 - npm install --build-from-source
 - copy %APPVEYOR_BUILD_FOLDER%\build\Release\wakanda_storage.node %APPVEYOR_BUILD_FOLDER%\bin
 - 7z a -ttar %APPVEYOR_BUILD_FOLDER%\build\Release\tmp.tar %APPVEYOR_BUILD_FOLDER%\bin
 - 7z a -tgzip %APPVEYOR_BUILD_FOLDER%\build\Release\wakanda_storage_win32.tar.gz %APPVEYOR_BUILD_FOLDER%\build\Release\tmp.tar
test_script:
 - npm test
 - npm run unit-tests
artifacts:
 path: build\Release\wakanda_storage_win32.tar.gz
 name: wakanda_storage_win32.tar.gz
deploy:
 description: 'windows release version'
 provider: GitHub    
 auth_token:
  secure: rW3KAItK5Sju8JdPRm88jpZw45RITtwW57cjXc/dSl7nOh3qZ9xxIB+AqnKMdJg0
# '%appveyorGithub%'
 artifact: build\Release\wakanda_storage_win32.tar.gz
 on:
  appveyor_repo_tag: true
  configuration: Release
