language: node_js
compiler:
  - clang
node_js:
 - node
os : 
 - linux
 - osx

env:
  - ARCHITECTURE="$TRAVIS_OS_NAME"
 
addons:
  apt:
    sources:
      - llvm-toolchain-precise-3.8
    packages:
      - cppcheck
      - llvm-dev
      - clang-3.8
before_install:
 - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ARCHITECTURE="darwin" ;fi
 - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo add-apt-repository 'deb http://llvm.org/apt/trusty/ llvm-toolchain-trusty-6.0 release' ;fi
 - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then curl -L 'http://llvm.org/apt/llvm-snapshot.gpg.key' | sudo apt-key add - ;fi
 - echo $ARCHITECTURE
 - echo $TRAVIS_OS_NAME
script:
 - npm install -g node-gyp
 - npm install -g node-pre-gyp
 - npm install  expect.js
 - npm install --build-from-source
 - node-pre-gyp configure
 - node-pre-gyp build
 - npm test
 - cd $TRAVIS_BUILD_DIR/test/cpp-tests
 - cmake -DCMAKE_BUILD_TYPE=Release
 - make cpp-tests
 - ./cpp-tests
# - cppcheck  -v --enable=all --language=c++ --std=c++11 . 
# - clang-tidy -checks='*' -p . src/*.cpp
 - mkdir $TRAVIS_BUILD_DIR/build/Release/bin
 - cp $TRAVIS_BUILD_DIR/build/Release/wakanda_storage.node $TRAVIS_BUILD_DIR/build/Release/bin
 - cd $TRAVIS_BUILD_DIR/build/Release
 - tar cfvz wakanda_storage_$ARCHITECTURE.tar.gz bin
 - cd $TRAVIS_BUILD_DIR
install:
 - npm install -g mocha
 - export cc=clang && export CXX=clang++
# - sudo apt-get install -qq cppcheck
# - sudo add-apt-repository 'deb http://llvm.org/apt/trusty/ llvm-toolchain-trusty-6.0 release'
# - curl -L http://llvm.org/apt/llvm-snapshot.gpg.key | sudo apt-key add -
# - sudo apt-get update
# - sudo apt-get install llvm-dev
deploy:
 - provider: releases
   email: social@wakanda.io
   api_key: $githubKey
   file: "$TRAVIS_BUILD_DIR/build/Release/wakanda_storage_$ARCHITECTURE.tar.gz"
   skip_cleanup: true
   on :
    all_branches: true
    repo: Wakanda/wakanda-storage
    tags: true
 - provider: npm
   email: social@wakanda.io
   api_key: $npmToken
   on:
    branch: master
    tags: true
